### ISSUE TITLE
Début opaque

### ISSUE THREAD

**Issue by ipante** [AnteJR/That_House#6]
Peut-être faut-il (tôt ou plutôt tard) mettre sur la piste de l'action attendue pour faire évoluer l'histoire. Un compteur du nombre de phrases validées pour un bref feedback ?

**Comment by AnteJR** [comment]
Solution #1 implémentée : des textes qui apparaissent au bout de 30-60s après avoir atteint "la fin" d'un acte

In progress - solution #2 : implémenter un compteur des phrases validées (we'll see how it goes)

**Comment by AnteJR** [comment]
Il y a désormais un compteur des actions possibles ET des indices qui se lancent automatiquement selon certaines conditions.
